"""
_shared_config.py
================
Shared constants for all PFAS ML pipeline scripts.

Centralises:
  * Path constants (PROJECT_ROOT, DATA_PAPER, DATA_PROCESSED, etc.)
  * NON_FEATURE column set (metadata columns to drop before modelling)
  * SOIL_FEATURES list (the 9 soil properties)
  * XGB_DEFAULT (XGBoost hyperparameters used across all training scripts)
  * SIMPLIFIED_FEATURES (the 4-feature MolWt + 3 soil minimal model)

All paper_*.py, prepare_*.py, verify_*.py, and gen_*.py scripts should
import from this module rather than redefining these constants. See
docs/REPRODUCE.md §13 (reproduction-report-2026-07-25.md, items 13.1-13.3)
for the historical motivation (consistency across 21 scripts).

Tested: 2026-07-25 (Windows 11, Python 3.11.9, XGBoost 3.2.0).
"""
import os

# ---------------------------------------------------------------------------
# Path constants
# ---------------------------------------------------------------------------
# scripts/ → project root (one level up from this file)
PROJECT_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), os.pardir))
DATA_SOURCE = os.path.join(PROJECT_ROOT, "data", "source")
DATA_RAW = os.path.join(PROJECT_ROOT, "data", "raw")
DATA_PROCESSED = os.path.join(PROJECT_ROOT, "data", "processed")
DATA_PAPER = os.path.join(PROJECT_ROOT, "data", "paper")
MANUSCRIPT = os.path.join(PROJECT_ROOT, "manuscript")
DOCS = os.path.join(PROJECT_ROOT, "docs")
SCRIPTS = os.path.join(PROJECT_ROOT, "scripts")
PAPER_DIR = os.path.join(PROJECT_ROOT, "paper")  # working notes (gitignored)

# Backwards-compatible aliases (some scripts use old names)
SI_DIR = DATA_PAPER  # legacy name for data/paper/

# Input files
FEATURE_MATRIX = os.path.join(DATA_PAPER, "feature_matrix_kd.csv")
PFAS_PROPERTIES = os.path.join(DATA_PAPER, "PFAS_Properties.csv")
FINAL_DATA = os.path.join(DATA_PAPER, "Final_data.csv")

# Output files (most common)
MODEL_RESULTS = os.path.join(DATA_PAPER, "kd_model_results.csv")
SHAP_IMPORTANCE = os.path.join(DATA_PAPER, "kd_shap_importance.csv")
SIMPLIFIED_RESULTS = os.path.join(DATA_PAPER, "kd_simplified_results.csv")
LOO_RESULTS_COMBINED = os.path.join(DATA_PAPER, "kd_leave_one_out_results_combined.csv")
LOO_SUMMARY = os.path.join(DATA_PAPER, "kd_leave_one_out_summary.csv")
TRANSFER_RESULTS = os.path.join(DATA_PAPER, "kd_transfer_results.csv")
NESTED_RESULTS = os.path.join(DATA_PAPER, "kd_nested_feature_selection.csv")
CLUSTER_VALIDATION = os.path.join(DATA_PAPER, "kd_cluster_validation.csv")
EXTERNAL_XIE = os.path.join(DATA_PAPER, "kd_external_validation_xie2024.csv")
EXTERNAL_MORALES = os.path.join(DATA_PAPER, "kd_external_validation_morales2026.csv")
EXTERNAL_FIGURE = os.path.join(DATA_PAPER, "fig10_external_validation.png")

# Derived long-format CSV from Morales SI (produced by paper_10 run)
MORALES_LONG = os.path.join(DATA_SOURCE, "morales_long.csv")

# 11K pipeline intermediates (gitignored, regenerated by prepare_*)
EPA_PFASMASTER = os.path.join(DATA_RAW, "pfas_master_list.csv")
PFAS_CID_LIST = os.path.join(DATA_RAW, "pfas_cid_list.csv")
PFAS_CLEAN = os.path.join(DATA_PROCESSED, "pfas_clean.csv")
PFAS_DESCRIPTORS_11K = os.path.join(DATA_PROCESSED, "pfas_descriptors_full.csv")
PFAS_FINGERPRINTS_11K = os.path.join(DATA_PROCESSED, "pfas_fingerprint_full.csv")

# Pretrained autoencoder (produced by paper_08, consumed by future re-runs)
PRETRAINED_ENCODER = os.path.join(DATA_PAPER, "pretrained_encoder.pt")

# External validation data sources (downloaded by user; not in repo for Xie)
XIE_SI_DOCX = os.path.join(DATA_SOURCE,
                            "Elucidating per- and polyfluoroalkyl2024-SI.docx")
MORALES_SI = os.path.join(DATA_SOURCE, "Morales_2026_SI.xlsx")

# ---------------------------------------------------------------------------
# Feature definitions
# ---------------------------------------------------------------------------
# Columns to drop from the feature matrix before modelling (metadata, not
# descriptors). Centralised here to eliminate per-script drift.
NON_FEATURE = {
    "PFAS_name",      # identifier, not a feature
    "log_Kd",         # target
    "Kd_L_kg",        # target (linear-scale, kept for reference)
    "log_Koc",        # derived alternative target
    "_n_soil_missing",  # internal quality flag; never present in output CSV
}

# The 9 soil properties used as covariates in the Combined model. Order
# matches the data dictionary; used by all scripts that subset to soil-only
# or report soil feature importance.
SOIL_FEATURES = [
    "Corg_%",   # organic carbon content (%)
    "foc",      # fraction of organic carbon
    "pH",       # soil pH
    "Sand",     # texture %
    "Silt",     # texture %
    "Clay",     # texture %
    "CEC",      # cation exchange capacity (cmol+/kg)
    "Fe_g_kg",  # iron content (g/kg)
    "Al_g_kg",  # aluminum content (g/kg)
]

# The 4-feature "simplified" model for high-throughput screening. See
# paper §3.5. Achieves 97% of the full-model R² with 1 molecular descriptor
# and 3 routinely measured soil properties.
SIMPLIFIED_FEATURES = ["MolWt", "Corg_%", "pH", "CEC"]

# The 2 SHAP-ranked molecular descriptors that individually reproduce the
# full RDKit model performance (R² ≈ 0.647).
TOP2_MOLECULAR = ["MolWt", "ExactMolWt"]

# ---------------------------------------------------------------------------
# XGBoost hyperparameters
# ---------------------------------------------------------------------------
# Defaults for the Combined (RDKit + soil) model and all variants. The
# `simplified_max_depth=4` variant uses shallower trees to avoid overfit
# on the 4-feature minimal model; this is applied via the
# `XGB_SIMPLIFIED` dict below.
XGB_DEFAULT = dict(
    n_estimators=500,
    max_depth=8,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    n_jobs=-1,
)

# For simplified / nested-feature-selection scripts: shallower trees.
XGB_SIMPLIFIED = dict(
    n_estimators=500,
    max_depth=4,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    n_jobs=-1,
)

# Legacy: used by some gen_*.py scripts. Kept as an alias for cross-platform
# determinism on Windows where over-subscription hurts; same hyperparameters
# otherwise.
XGB_SINGLE_THREAD = dict(
    n_estimators=500,
    max_depth=4,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    n_jobs=1,
)

# ---------------------------------------------------------------------------
# Convenience helpers
# ---------------------------------------------------------------------------
def soil_only_features():
    """Return copy of SOIL_FEATURES for use as feature subset."""
    return list(SOIL_FEATURES)


def feature_matrix_path():
    """Return absolute path to feature_matrix_kd.csv (canonical training input)."""
    return FEATURE_MATRIX


def make_xgb(**overrides):
    """Construct an XGBRegressor with XGB_DEFAULT, optionally overriding.

    Usage:
        from _shared_config import make_xgb
        model = make_xgb()                          # Combined default
        model = make_xgb(max_depth=4)               # Simplified
        model = make_xgb(n_jobs=1)                  # Single thread (Windows)
    """
    from xgboost import XGBRegressor
    cfg = {**XGB_DEFAULT, **overrides}
    return XGBRegressor(**cfg)
